name: Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Build FreeImage
      run: |
        chmod a+x scripts/build-android.py
        python scripts/build-android.py /opt/unity/Editor
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: libFreeImage.so
        path: build/libFreeImage.so
