name: Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2021.3.14f1-android-1.0.1
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Build FreeImage
      run: |
        apt update -y
        apt install cmake -y
        apt install build-essential -y
        chmod a+x scripts/build-android.py
        python scripts/build-android.py /opt/unity/Editor
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: "arm64-v8a"
        path: build-arm64-v8a/libFreeImage.so
    - uses: actions/upload-artifact@v3
      with:
        name: "armeabi-v7a"
        path: build-armeabi-v7a/libFreeImage.so

